SergioBenitez/cookie-rs

Cargo.toml
src/jar.rs
src/lib.rs

Bump the OpenSSL version to 0.5, since some other projects (handlebars-iron) have a dependency to that, and cargo can't mix the versions. OpenSSL uses the new IO, so updated that too.
FIXME: OpenSSL now returns the amount of bytes written to HMAC. Should we continue ignoring it, or check?

OpenSSL 0.4 -> 0.5, new IO

---

Cargo.toml

upgrade openssl so that framework like nickel.rs can build pass.

upgrade openssl to v0.6

---

src/lib.rs

percent_decode, percent_encode, and DEFAULT_ENCODE_SET were moved to the percent_encoding module in https://github.com/servo/rust-url/commit/54b97f14bd24eacf2e9eaa089d9ee5be7fd2aa1c

unbreak build

---

Cargo.toml
src/lib.rs

It is not practical for some packages to pull a dependency on openssl,
but they want to use cookie parsing, so compiling with
--no-default-features removes the cookie jar and with this the dependency
on openssl.
As discussed in hyperium/hyper#433

Add no-default-features, providing just the parsing functionality

---

Cargo.toml
src/jar.rs
src/lib.rs

The `secure` module and the `signed` and `encrypted` methods are the
only parts of `jar` that depend on `openssl`, so this adds all the other
parts of jar to be used even without those crates.

include jar even if secure feature is disabled

---

Cargo.toml
src/lib.rs

**Do not merge yet:** rust-url 1.0 is not published yet and may still get breaking changes. The goal of this PR for now is to demonstrate API usage.
Depends on https://github.com/servo/rust-url/pull/176

Update to rust-url 1.0

---

.travis.yml
Cargo.toml
src/lib.rs

It was recommended in this pull [request](https://github.com/servo/servo/pull/10800) for servo that I placed the derive attribute for the RustcEncodable and RustcDecodable traits for the cookie_rs:Cookie to avoid encoding and decoding manually.  I noticed in the time library that the  #[cfg] attribute is used to make the encodable/decodable attribute optional.  If you would like me to add the #[cfg] attribute just let me know!
Edit: Actually I went ahead and added the #[cfg] attribute because rustc-serialize is marked as optional in Cargo.toml

Add RuctcEncdoable and RustcDecodable to derive attribute for Cookie

---

.travis.yml
Cargo.toml
src/lib.rs

Implement `serde::Serialize` and `serde::Deserialize` for `Cookie` and add it behind the `serialize-serde` feature. This is largely done to allow for `Cookie` to be sent across servo `ipc-channel`s.
Critiques are very welcome. There might be a better way of doing this.
NB: `Cookie::custom` was not included in this PR.
Related to: servo/servo#10826
CC @asajeffrey
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/alexcrichton/cookie-rs/48)

Implement serde serialization for Cookie

---

src/lib.rs

I encountered an issue when serialising cookies so that they can be reused between invocations of a tool I'm writing. If the cookie value contains a percent encoded `;` it is serialised with percent encodings resolved. When the cookie is read back in the value is truncated after the first `;`. I'm not quite sure what the fix is so I added a failing test in this PR to demonstrate the issue. It seems this may be related to https://github.com/alexcrichton/cookie-rs/issues/40.
Sample test run:
```
cargo test --features serialize-serde
Running target/debug/cookie-00ccfac4debcd91d
running 8 tests
test tests::odd_characters ... ok
test tests::pair ... ok
test jar::test::simple ... ok
test jar::test::permanent ... ok
test tests::parse ... ok
test tests::test_serialize ... ok
test …
```

Fix handling of cookies with ; in value

---

src/lib.rs

Adds the `#[deny(missing_docs)]` attribute and add docs to get it to
compile

HBump to 0.3.1

---

.travis.yml
Cargo.toml
README.md
src/builder.rs
src/jar.rs
src/lib.rs
src/parse.rs

Hello!
This pull request presents the largest change to the crate since its creation. It completely rewrites the `Cookie` structure and API. The major benefits of this rewrite are usability and performance. On the usability side, a structure following the builder pattern has been added as the primary way to construct a `Cookie`. On the performance side, parsing is now completely allocation free, and setting fields in an existing `Cookie` structure can be done in an allocation free way as well.
The summary of changes, from the main commit, is as follows:
* `Cookie` parsing is allocation-free.
* All fields in `Cookie` can be set allocation-free.
* A `Cookie` can have a non-static lifetime.
* All methods in `Cookie` are documented with examples.
* A `Cookie` can be built via a new builder …

Overhaul Cookie Crate

---

Cargo.toml
README.md
src/builder.rs
src/delta.rs
src/jar.rs
src/lib.rs
src/parse.rs
src/secure/key.rs
src/secure/macros.rs
src/secure/mod.rs
src/secure/private.rs
src/secure/signed.rs

This commit completely rewrites `CookieJar` so that it is more efficient while being simpler and more correct overall. At a high-level, a `CookieJar` now returns borrows to `Cookie` structures whenever possible. `CookieJar` and children jars (now `PrivateJar` and `SignedJar`) are distinct types. The "encrypted" child jar has been replaced by `PrivateJar` which uses authenticated encryption. All crypto is done via `ring`.
A detailed list of changes is below:
* The "permanent" child jar has been removed.
* A `make_permanent` method has been added to `Cookie`.
* A `permanent` method has been added to `CookieBuilder`.
* A `named` constructor has been added to `Cookie`.
* `CookieJar` no longer has a generic lifetime parameter.
* A `CookieJar` no longer contains `RefCell`s.
* …

Overhaul `CookieJar`: more efficient, more secure, more docs.

---

src/lib.rs

Added some new methods to get strings with longer lifetimes if they are in the backing storage of the Cookie.
This is still WIP; the names are provisional, no tests implemented and the docstrings aren't up to date.
What do you think about this idea? Certainly less invasive than my earlier experiment. If it seems fine, I'll finish this up.

Added some new methods to get strings with longer lifetimes

---

src/parse.rs

Duration will panic if the number of seconds is greater than 2^63/1000. This just caps the Max-Age to the highest value we can parse.

Don't panic if passed in a large max age.

---

Cargo.toml
src/secure/key.rs
src/secure/private.rs

base64 0.5.2 fixes a security vulnerability. *ring* 0.9 is used by the
latest version of Rustls and some other crates.

0.8.0: Update to base64 0.5.2 and *ring* 0.9.1.

---

Cargo.toml

Before ring 0.9.3, it was possible to link multiple versions of ring into a program, e.g. if one version depended on ring 0.6 and another dependend on ring 0.9. Unfortunately, this doesn't work, because the linker doesn't know to how to link ring's C/asm code correctly in that kind of situation. ring 0.9.3 added a flag to its Cargo.toml to tell the Rust toolchain to stop allowing multiple versions of ring to be linked into the same program, to prevent any problems this may cause.
ring 0.9.4 was released with an update to make some crates easier to update to 0.9.x.

Update to *ring* 0.9.4.

---

Cargo.toml

Please upgrade ring. I'm having to manually freeze another project of mine to 9.4 that is using ring 0.11.0. Thanks.

upgrade ring to 0.11.0

---

src/jar.rs

This patch prevents the possibility that the order of internal iterators in [`hash_set::Union`](https://doc.rust-lang.org/nightly/std/collections/hash_set/struct.Union.html) will be changed, caused by the change in rust-lang/rust#57043.

force the order of the internal iterators in Iter

---

src/secure/key.rs

I ran into a small issue with `OnceLock<Key>::set()` because it returns a `Result<(), Key>` which requires `Key` to impl `Debug` for `expect()` and `unwrap()` to be implemented. Also allows deriving `Debug` for structs which include a `Key`.

Implement Debug for Key

---

src/builder.rs

Add a `removal` method to the `CookieBuilder`, which acts as a counterpart to the `make_removal` method of the `Cookie`.
This is analogous to the `permanent` method of the `CookieBuilder`, which is a counterpart to the `make_permanent` method of the `Cookie`.

Allow creating a removal cookie via the builder
